### ISSUE TITLE
The album in super topic (超级话题) can not be downloaded

### ISSUE THREAD

**Issue by CharlesLiu7** [Lodour/Weibo-Album-Crawler#12]
I am going to download the whole photos in a super topic, e.g. [super topic: 动物](https://www.weibo.com/p/10080883d7b8a4ba9ca03c1e863198265ea9fa/topic_album?from=page_100808&mod=TAB#place), I try to add `https://www.weibo.com/p/10080883d7b8a4ba9ca03c1e863198265ea9fa` to the `TARGETS`, and get exception. Because in super topic, the photos are not organized by **albums** but in waterfall style. 

So, how can I download photos in super topic 😭 ?

![](https://scorpio.ga/~charles/bugs/Weibo-Album-Crawler/animal.png)

**Comment by Lodour** [comment]
You can use the Developer Tools of your browser to figure out:
1. The actual URL that returns a group of picture's meta-data, like `mid`, `pid`.
2. How such meta-data is converted into the actual URL of the pictures.

**Comment by CharlesLiu7** [comment]
I find an api to get the large photo link which is different with your way.

API format:
```
http://photo.weibo.com/$uid/wbphotos/large/mid/$mid/pid/$pid
```
the parameters in the API are the photo's `uid`, `mid` and `pid`, and in the API webpage there exists the large photo url.

Thanks a lot!

**Comment by CharlesLiu7** [comment]
I write a repo to download the super topic album, it's [here](https://github.com/CharlesLiu7/Weibo-SuperTopic-Album-Crawler)

我新建了个repo来下载超级话题的相册，[链接](https://github.com/CharlesLiu7/Weibo-SuperTopic-Album-Crawler)。
