### ISSUE TITLE
这是什么情况？

### ISSUE THREAD

**Issue by zackaryhuang** [Lodour/Weibo-Album-Crawler#13]
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    Crawler(target).start()
  File "/Users/peter/Downloads/spider/Weibo-Album-Crawler/weibo/core.py", line 24, in __init__
    self.uid, self.name = self.target['oid'], self.target['onick']
KeyError: 'oid'

**Comment by Lodour** [comment]
默认情况下，登陆成功了才会有 `oid` 这个键。
如果你确认 Cookies 有效，可能是新浪的一些设定有所变化，可以尝试抓包看一看。

**Comment by CharlesLiu7** [comment]
@Peter-Huang0623 大概率是因为你没有登录成功，我的经验是[这个](https://github.com/Lodour/Weibo-Album-Crawler/issues/10#issuecomment-443644272)

**Comment by roachsinai** [comment]
![screenshot_20190127_171748](https://user-images.githubusercontent.com/9500049/51799067-80ce1780-2257-11e9-92f6-55a4c1c8be1a.png)

配置文件只有第一项在cookie中：
https://github.com/Lodour/Weibo-Album-Crawler/blob/1bdb940b0963f2fcb3f06cee8bddb03e1b6a53ef/settings.sample.py#L24

**Comment by Lodour** [comment]
@roachsinai 这只是一个样例，你需要以你自己的 Cookies 为准。

**Comment by roachsinai** [comment]
好的。谢谢。
