### ISSUE TITLE
ValueError: dictionary update sequence element #0 has length 5, 2 is required

### ISSUE THREAD

**Issue by SpriggyDesmond** [Lodour/Weibo-Album-Crawler#14]
`COOKIES = 'SINAGLOBAL=4x0; __gads=ID=9x5c:T=15x49:S=ALxxeA; _ga=GA1.2.1898901070.1501506516;....'
`
测试Cookie如上，但`__gads=ID=9x5c:T=15x49:S=ALxxeA; `这个会引起错误
其次程序是按照`;(空格)`分割的，删掉这一行之后也花了一阵子才反应过来哪里出了问题。
可以优化一下Cookie的分割法。

**Comment by Lodour** [comment]
* 处理了多个等号 `=` 的情况。
* 请重新登陆一次微博，防止别人恶意使用你发出来的 Cookies。

**Comment by SpriggyDesmond** [comment]
Thanks for the quick response.
