### ISSUE TITLE
请问怎样访问自己相册专辑页面时的Cookies？我用的mac上的Safari浏览器

### ISSUE THREAD

**Issue by lorraine2015** [Lodour/Weibo-Album-Crawler#2]
搜了一下Safari的cookies在~/Library/Cookies下，结果也没有找到微博的cookies
是否能解答一下，非常感谢

**Comment by Lodour** [comment]
是通过抓包获取的，Safari貌似在`开发-Web检查器`里可以看到Cookies。

如果用Chrome可以在开发者工具中直接抓包获取。

具体粘贴的Cookies格式大致为：
```
login_sid_t=****; _s_tentry=**; Apache=***; SINAGLOBAL=***; ULV=***; un=***; ....;
```

**Comment by lorraine2015** [comment]
好的，已搞定。多谢了！
